#!/bin/bash

# Get the input date from the command line argument
input_date=$1

# Template definition
template='+%Y-%m-%d||OFFSET=+5'

# Splitting the template by '||'
IFS='||' read -r format offset <<< "$template"

# Extracting the date format from the first part of the template
date_format=$(echo "$format" | cut -d'+' -f1)

# Extracting the offset value from the second part of the template
offset_value=$(echo "$offset" | cut -d'=' -f2)

# Calculating the new date based on the offset
new_date=$(date -d "$input_date $offset_value days" "+$date_format")

# Printing the new date
echo "$new_date"


##############

#!/bin/bash

# Define the string
input_string="CURR_DATE||+%y-%m-%d||OFFSET=+5"

# Split the string by "||"
IFS='||' read -r var1 var2 var3 <<< "${input_string//||/|}"

# Print each variable
echo "Variable 1: $var1"
echo "Variable 2: $var2"
echo "Variable 3: $var3"

########################################


#!/bin/bash

# Input string
input="CURR_DATE||+%Y-%m-%d||OFFSET=+5"

# Split the input string by "||"
IFS="||" read -ra parts <<< "$input"

# Print all parts
for part in "${parts[@]}"; do
    echo "Part: $part"
done

# Check if the first part is "CURR_DATE"
if [[ "${parts[0]}" == "CURR_DATE" ]]; then
    # Get the format from the second part
    format="${parts[1]}"
    # Get the offset from the third part
    offset=$(echo "${parts[2]}" | cut -d'=' -f2)
    
    # Get the current system date
    current_date=$(date +"$format")

    # Apply offset to the current date
    next_date=$(date -d "$current_date $offset day" +"$format")
    
    echo "Current date: $current_date"
    echo "Next date: $next_date"
fi
